<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Karyawan;
use Carbon\Carbon;

class KaryawanSeeder extends Seeder
{
    /**
     * Seed karyawan dengan data yang sinkron dengan SystemSettingSeeder
     */
    public function run(): void
    {
        $this->command->info('Seeding Karyawan...');
        
        $karyawans = [
            [
                'nama_karyawan' => 'Budi Santoso',
                'email' => 'budi.santoso@ptpsf.com',
                'no_telp' => '081234567890',
                'join_date' => Carbon::now()->subYears(3),
                'masa_kerja' => 36,
                'jabatan' => 'Manager',
                'lokasi_kerja' => 'Central Java',
                'jenis_karyawan' => 'Organik',
                'status_pegawai' => 'Kontrak',
                'npwp' => '12.345.678.9-012.000',
                'bpjs_kesehatan_no' => '0001234567890',
                'bpjs_kecelakaan_kerja_no' => '0001234567890',
                'bpjs_tk_no' => '0001234567890',
                'no_rekening' => '1234567890',
                'bank' => 'BCA',
                'status_perkawinan' => 'Kawin',
                'nama_istri' => 'Siti Nurhaliza',
                'jumlah_anak' => 2,
                'no_telp_istri' => '081234567891',
                'status_karyawan' => 'Active',
            ],
            [
                'nama_karyawan' => 'Ahmad Fauzi',
                'email' => 'ahmad.fauzi@ptpsf.com',
                'no_telp' => '081234567892',
                'join_date' => Carbon::now()->subYears(2),
                'masa_kerja' => 24,
                'jabatan' => 'Senior Engineer',
                'lokasi_kerja' => 'East Java',
                'jenis_karyawan' => 'Konsultan',
                'status_pegawai' => 'Kontrak',
                'npwp' => '12.345.678.9-013.000',
                'bpjs_kesehatan_no' => '0001234567891',
                'bpjs_kecelakaan_kerja_no' => '0001234567891',
                'bpjs_tk_no' => '0001234567891',
                'no_rekening' => '2234567890',
                'bank' => 'Mandiri',
                'status_perkawinan' => 'Belum Kawin',
                'nama_istri' => null,
                'jumlah_anak' => 0,
                'no_telp_istri' => null,
                'status_karyawan' => 'Active',
            ],
            [
                'nama_karyawan' => 'Dewi Lestari',
                'email' => 'dewi.lestari@ptpsf.com',
                'no_telp' => '081234567893',
                'join_date' => Carbon::now()->subYears(1)->subMonths(6),
                'masa_kerja' => 18,
                'jabatan' => 'Finance',
                'lokasi_kerja' => 'Central Java',
                'jenis_karyawan' => 'Organik',
                'status_pegawai' => 'Kontrak',
                'npwp' => '12.345.678.9-014.000',
                'bpjs_kesehatan_no' => '0001234567892',
                'bpjs_kecelakaan_kerja_no' => '0001234567892',
                'bpjs_tk_no' => '0001234567892',
                'no_rekening' => '3234567890',
                'bank' => 'BNI',
                'status_perkawinan' => 'Kawin',
                'nama_istri' => null,
                'jumlah_anak' => 1,
                'no_telp_istri' => null,
                'status_karyawan' => 'Active',
            ],
            [
                'nama_karyawan' => 'Eko Prasetyo',
                'email' => 'eko.prasetyo@ptpsf.com',
                'no_telp' => '081234567894',
                'join_date' => Carbon::now()->subYear(),
                'masa_kerja' => 12,
                'jabatan' => 'Junior Engineer',
                'lokasi_kerja' => 'West Java',
                'jenis_karyawan' => 'Teknisi',
                'status_pegawai' => 'OJT',
                'npwp' => null,
                'bpjs_kesehatan_no' => '0001234567893',
                'bpjs_kecelakaan_kerja_no' => '0001234567893',
                'bpjs_tk_no' => '0001234567893',
                'no_rekening' => '4234567890',
                'bank' => 'BRI',
                'status_perkawinan' => 'Belum Kawin',
                'nama_istri' => null,
                'jumlah_anak' => 0,
                'no_telp_istri' => null,
                'status_karyawan' => 'Active',
            ],
            [
                'nama_karyawan' => 'Fitri Handayani',
                'email' => 'fitri.handayani@ptpsf.com',
                'no_telp' => '081234567895',
                'join_date' => Carbon::now()->subMonths(8),
                'masa_kerja' => 8,
                'jabatan' => 'Senior Installer',
                'lokasi_kerja' => 'Bali',
                'jenis_karyawan' => 'Teknisi',
                'status_pegawai' => 'Harian',
                'npwp' => null,
                'bpjs_kesehatan_no' => '0001234567894',
                'bpjs_kecelakaan_kerja_no' => '0001234567894',
                'bpjs_tk_no' => '0001234567894',
                'no_rekening' => '5234567890',
                'bank' => 'CIMB Niaga',
                'status_perkawinan' => 'Belum Kawin',
                'nama_istri' => null,
                'jumlah_anak' => 0,
                'no_telp_istri' => null,
                'status_karyawan' => 'Active',
            ],
            [
                'nama_karyawan' => 'Gunawan Wijaya',
                'email' => 'gunawan.wijaya@ptpsf.com',
                'no_telp' => '081234567896',
                'join_date' => Carbon::now()->subMonths(6),
                'masa_kerja' => 6,
                'jabatan' => 'Team Leader (junior)',
                'lokasi_kerja' => 'Central Java',
                'jenis_karyawan' => 'Borongan',
                'status_pegawai' => 'Harian',
                'npwp' => null,
                'bpjs_kesehatan_no' => null,
                'bpjs_kecelakaan_kerja_no' => null,
                'bpjs_tk_no' => null,
                'no_rekening' => '6234567890',
                'bank' => 'BSI',
                'status_perkawinan' => 'Belum Kawin',
                'nama_istri' => null,
                'jumlah_anak' => 0,
                'no_telp_istri' => null,
                'status_karyawan' => 'Active',
            ],
            [
                'nama_karyawan' => 'Hendra Kusuma',
                'email' => 'hendra.kusuma@ptpsf.com',
                'no_telp' => '081234567897',
                'join_date' => Carbon::now()->subYears(1)->subMonths(3),
                'masa_kerja' => 15,
                'jabatan' => 'Senior Leader',
                'lokasi_kerja' => 'West Java',
                'jenis_karyawan' => 'Organik',
                'status_pegawai' => 'Kontrak',
                'npwp' => '12.345.678.9-015.000',
                'bpjs_kesehatan_no' => '0001234567895',
                'bpjs_kecelakaan_kerja_no' => '0001234567895',
                'bpjs_tk_no' => '0001234567895',
                'no_rekening' => '7234567890',
                'bank' => 'BCA',
                'status_perkawinan' => 'Kawin',
                'nama_istri' => 'Rina Wati',
                'jumlah_anak' => 1,
                'no_telp_istri' => '081234567898',
                'status_karyawan' => 'Non-Active',
            ],
            [
                'nama_karyawan' => 'Indra Permana',
                'email' => 'indra.permana@ptpsf.com',
                'no_telp' => '081234567899',
                'join_date' => Carbon::now()->subYears(2)->subMonths(6),
                'masa_kerja' => 30,
                'jabatan' => 'Project Manager',
                'lokasi_kerja' => 'Central Java',
                'jenis_karyawan' => 'Konsultan',
                'status_pegawai' => 'Kontrak',
                'npwp' => '12.345.678.9-016.000',
                'bpjs_kesehatan_no' => '0001234567896',
                'bpjs_kecelakaan_kerja_no' => '0001234567896',
                'bpjs_tk_no' => '0001234567896',
                'no_rekening' => '8234567890',
                'bank' => 'Mandiri',
                'status_perkawinan' => 'Kawin',
                'nama_istri' => 'Lina Marlina',
                'jumlah_anak' => 2,
                'no_telp_istri' => '081234567900',
                'status_karyawan' => 'Resign',
            ],
        ];

        foreach ($karyawans as $data) {
            Karyawan::create($data);
        }

        $this->command->info('Karyawan seeded successfully! Created ' . count($karyawans) . ' karyawan.');
        $this->command->info('  - Active: 6 karyawan');
        $this->command->info('  - Non-Active: 1 karyawan');
        $this->command->info('  - Resign: 1 karyawan');
    }
}
